# This is a basic workflow to help you get started with Actions

name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1.6.0
        with:
          version: '1.6'
          arch: 'x64' # optional, default is x64
          show-versioninfo: 'true' # optional, default is false
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
#name: Run tests

#on: [push, pull_request]

#jobs:
#  test:
#   runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        julia-version: ['1.0', '1', 'nightly']
#        julia-arch: [x64, x86]
#        os: [ubuntu-latest, windows-latest, macOS-latest]
#        exclude:
#          - os: macOS-latest
#            julia-arch: x86

#    steps:
#      - uses: actions/checkout@v2
#      - uses: julia-actions/setup-julia@v1
#        with:
#          version: ${{ matrix.julia-version }}
#          arch: ${{ matrix.julia-arch }}
#      - uses: julia-actions/julia-buildpkg@v1
#      - uses: julia-actions/julia-runtest@v1
